### ISSUE TITLE
Publish latest version - 0.0.3

### ISSUE THREAD

**Issue by Jarred-Sumner** [sreekanthgs/bip_mnemonic#5]
The current version published on RubyGems does not seem to work with Ruby 2.5.1 or later.

```
undefined method `pseudo_bytes' for OpenSSL::Random:Module
```

This is fixed in `0.0.3`. 

But, `0.0.3` is not published.

If you publish the latest version, more people might use this package.

**Comment by sreekanthgs** [comment]
Thank you for pointing this out @Jarred-Sumner 
Version 0.0.3 is now pushed to ruby-gems.
